export const voices = [
  { id: "Zephyr", name: "زفیر (روشن)" },
  { id: "Puck", name: "پاک (شاداب)" },
  { id: "Charon", name: "کارون (آگاهی‌بخش)" },
  { id: "Kore", name: "کوره (قاطع)" },
  { id: "Fenrir", name: "فنریر (هیجان‌زده)" },
  { id: "Leda", name: "لدا (جوان)" },
  { id: "Orus", name: "اوروس (قاطع)" },
  { id: "Aoede", name: "آئوده (با طراوت)" },
  { id: "Callirrhoe", name: "کالیرو (آسان‌گیر)" },
  { id: "Autonoe", name: "آتونوئه (روشن)" },
  { id: "Enceladus", name: "انسلادوس (نفس‌دار)" },
  { id: "Iapetus", name: "یاپتوس (شفاف)" },
  { id: "Umbriel", name: "اومبریل (آسان‌گیر)" },
  { id: "Algieba", name: "الجبا (نرم)" },
  { id: "Despina", name: "دسپینا (نرم)" },
  { id: "Erinome", name: "ارینومه (شفاف)" },
  { id: "Algenib", name: "الجنیب (خشن)" },
  { id: "Rasalgethi", name: "رأس‌الجاثی (آگاهی‌بخش)" },
  { id: "Laomedeia", name: "لائومدیا (شاداب)" },
  { id: "Achernar", name: "آچرنار (نرم)" },
  { id: "Alnilam", name: "النظام (قاطع)" },
  { id: "Schedar", name: "صدر (یکنواخت)" },
  { id: "Gacrux", name: "گاکروکس (بالغ)" },
  { id: "Pulcherrima", name: "پولکریما (پیشرو)" },
  { id: "Achird", name: "اچیرد (دوستانه)" },
  { id: "Zubenelgenubi", name: "زبان‌الجنوبی (غیررسمی)" },
  { id: "Vindemiatrix", name: "ویندمیاتریکس (ملایم)" },
  { id: "Sadachbia", name: "سعدالاخبیه (سرزنده)" },
  { id: "Sadaltager", name: "سعدالتاجر (مطلع)" },
  { id: "Sulafat", name: "سولافات (گرم)" }
];

export const audioTags = [
  { tag: "[whispers]", label: "[نجوا]" },
  { tag: "[laughs]", label: "[خنده]" },
  { tag: "[sighs]", label: "[آه]" },
  { tag: "[gasp]", label: "[نفس‌گیر]" },
  { tag: "[cough]", label: "[سرفه]" },
  { tag: "[excitedly]", label: "[با هیجان]" },
  { tag: "[bored]", label: "[بی‌حوصله]" },
  { tag: "[reluctantly]", label: "[با بی‌میلی]" },
  { tag: "[very fast]", label: "[خیلی سریع]" },
  { tag: "[very slow]", label: "[خیلی کند]" },
  { tag: "[sarcastically]", label: "[با طعنه]" }
];
